### ISSUE TITLE
model intput

### ISSUE THREAD

**Issue by www516717402** [Wulingtian/nanodet_tensorrt_int8#3]
Thank your for open this project.
**.trt is int8 model, however input data is float. [code](https://github.com/Wulingtian/nanodet_tensorrt_int8/blob/beabc5062830e58b8b244c086439d19c335c94e2/nanodet_infer.cc#L322)

**Comment by Wulingtian** [comment]
输入数据为float类型，不影响int8模型推理

**Comment by www516717402** [comment]
@Wulingtian 
- 模型参数是int8，输入时float，那中间计算需要混合来算，这样肯定会降低效率。
- 直接输入int8有点不现实，一般进网络都得归一化（mean，std）

**Comment by www516717402** [comment]
关闭此问题：和输入无关，结合量化过程，前向计算中间会转换img为float类型。
